name: Build module release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 设置为 0 以获取所有标签历史

      - name: Install 7z
        uses: edgarrc/action-7z@v1.0.5

      - name: Get current time
        run: |
          timestamp_with_random="$(date +'%Y%m%d')"
          echo "$timestamp_with_random" > current_time.txt

      - name: Get latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "$LATEST_TAG" > latest_tag.txt

      - name: Make module.prop and prepare files
        run: |
          LATEST_TAG=$(cat latest_tag.txt)
          CURRENT_TIME=$(cat current_time.txt)
          . ./module_settings/config.sh
          echo "id=${action_id}" > module.prop
          echo "name=${action_name}" >> module.prop
          echo "version=${LATEST_TAG}" >> module.prop
          echo "versionCode=${CURRENT_TIME}" >> module.prop
          echo "author=${action_author}" >> module.prop
          echo "description=${action_description}" >> module.prop
          mkdir bin

      - name: Replace module ID in files
        run: |
          . ./module_settings/config.sh
          # 替换文件中的模块ID
          find files -name "*.sh" -exec sed -i "s/AMMF/${action_id}/g" {} \;
          find webroot -name "*.js" -exec sed -i "s/AMMF/${action_id}/g" {} \;
          find src -name "*.cpp" -exec sed -i "s/AMMF2/${action_id}/g" {} \;
          sed -i "s/AMMF/${action_id}/g" webroot/index.html
          echo "已完成模块ID替换"
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Build filewatch for aarch64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -O2 -Wall -Wextra -static-libstdc++ -o bin/filewatch-aarch64 src/filewatch.cpp

      - name: Build filewatch for x86_64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ \
          -O2 -Wall -Wextra -static-libstdc++ -o bin/filewatch-x86_64 src/filewatch.cpp

      - name: Build logmonitor for aarch64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -O2 -Wall -Wextra -std=c++11 -static-libstdc++ -o bin/logmonitor-aarch64 src/logmonitor.cpp

      - name: Build logmonitor for x86_64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ \
          -O2 -Wall -Wextra -std=c++11 -static-libstdc++ -o bin/logmonitor-x86_64 src/logmonitor.cpp

      - name: Build process_manager for aarch64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
          -O2 -Wall -Wextra -std=c++11 -static-libstdc++ -o bin/process_manager-aarch64 src/process_manager.cpp -llog
      
      - name: Build process_manager for x86_64
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ \
          -O2 -Wall -Wextra -std=c++11 -static-libstdc++ -o bin/process_manager-x86_64 src/process_manager.cpp -llog

      - name: Strip binaries
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/filewatch-aarch64 || echo "Failed to strip aarch64 binary"
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/filewatch-x86_64 || echo "Failed to strip x86_64 binary"
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/logmonitor-aarch64 || echo "Failed to strip logmonitor aarch64 binary"
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/logmonitor-x86_64 || echo "Failed to strip logmonitor x86_64 binary"
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/process_manager-aarch64 || echo "Failed to strip process_manager aarch64 binary"
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip bin/process_manager-x86_64 || echo "Failed to strip process_manager x86_64 binary"

      - name: Remove files
        run: |
          rm -f src/*.cpp
          rm build.sh

      - name: Compress files
        run: |
          LATEST_TAG=$(cat latest_tag.txt)
          . ./settings/settings.sh
          7z a -r -mx9 "${action_name}_${LATEST_TAG}.zip" * -x!*.git* -x!*.zip -x!latest_tag.txt -x!current_time.txt -x!requirements.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
